//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int post_id { get; set; }
        public int user_id { get; set; }
        public int image_id { get; set; }

        [Required(ErrorMessage = "Title is required"), StringLength(10, MinimumLength = 2, ErrorMessage = "The title must have between 2 and 10 characters.")]
        public string title { get; set; }

        [Required(ErrorMessage = "Description is required"), StringLength(100, MinimumLength = 10, ErrorMessage = "The description must be between 10 and 100 characters.")]
        public string description { get; set; }

        public System.DateTime created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Image Image { get; set; }
        public virtual User User { get; set; }
    }
}
